# This config file for Travis CI utilizes ros-industrial/industrial_ci package.
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst
sudo: required 
dist: trusty 
services:
  - docker
language: generic 
compiler:
  - gcc
notifications:
  email:
    on_failure: always
    recipients:
      - peckama2@fel.cvut.cz
env:
  global:
    - BEFORE_SCRIPT=".travis/upgrade_pip.sh"
    - ROSDEP_SKIP_KEYS="tensorflow_catkin"
  matrix:
    - ROS_DISTRO="indigo" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu ROSINSTALL_FILENAME=".travis/rosinstall_ci_old_abi" UPSTREAM_WORKSPACE="file"  BEFORE_SCRIPT=".travis/upgrade_pip.sh && pip install --ignore-installed six && pip install tensorflow"
    - ROS_DISTRO="kinetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu ROSINSTALL_FILENAME=".travis/rosinstall_ci_new_abi" UPSTREAM_WORKSPACE="file" CATKIN_CONFIG="-DFORCE_TF_PIP_SEARCH=1"
    - ROS_DISTRO="melodic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu ROSINSTALL_FILENAME=".travis/rosinstall_ci_new_abi" UPSTREAM_WORKSPACE="file" CATKIN_CONFIG="-DFORCE_TF_PIP_SEARCH=1"
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .industrial_ci
script:
  - source .industrial_ci/travis.sh
